/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package parqueadero.presentacion;

import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import parqueadero.negocio.Conductor;
import parqueadero.negocio.GestorPrincipal;
import parqueadero.negocio.Vehiculo;

/**
 *
 * @author familia
 */
public class GUIBuscarConductor extends javax.swing.JInternalFrame {

    /**
     * Creates new form GUIBuscarConductor
     */
    
    private GestorPrincipal gestor;
    private MapaParqueadero objMapa;
    private Conductor objCon;
    private Vehiculo objVeh;
    public GUIBuscarConductor(GestorPrincipal gestor, MapaParqueadero objMapa) {
        initComponents();
        this.gestor = gestor;
        this.objMapa = objMapa;
                
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanelBuscar = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jComboBoxCampoBusqueda = new javax.swing.JComboBox<String>();
        jtextCampoEscrituraBusqueda = new javax.swing.JTextField();
        jButtonBuscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableVehiculos = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jButtonAsignarLugar = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextNombre = new javax.swing.JTextField();
        jTextId = new javax.swing.JTextField();
        jTextCarnet = new javax.swing.JTextField();
        jTextGenero = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextRol = new javax.swing.JTextField();

        jPanelBuscar.setBorder(javax.swing.BorderFactory.createTitledBorder("Buscar Conductor"));
        jPanelBuscar.setMinimumSize(new java.awt.Dimension(300, 350));
        jPanelBuscar.setPreferredSize(new java.awt.Dimension(300, 350));
        jPanelBuscar.setLayout(new java.awt.GridBagLayout());

        jLabel3.setText("Elija un campo para buscar:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.insets = new java.awt.Insets(25, 0, 0, 0);
        jPanelBuscar.add(jLabel3, gridBagConstraints);

        jComboBoxCampoBusqueda.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Cedula", "Codigo" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(23, 0, 0, 0);
        jPanelBuscar.add(jComboBoxCampoBusqueda, gridBagConstraints);

        jtextCampoEscrituraBusqueda.setMinimumSize(new java.awt.Dimension(80, 20));
        jtextCampoEscrituraBusqueda.setPreferredSize(new java.awt.Dimension(80, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(24, 0, 0, 33);
        jPanelBuscar.add(jtextCampoEscrituraBusqueda, gridBagConstraints);

        jButtonBuscar.setText("Buscar");
        jButtonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 10;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(23, 0, 0, 0);
        jPanelBuscar.add(jButtonBuscar, gridBagConstraints);

        jScrollPane1.setMinimumSize(new java.awt.Dimension(400, 95));
        jScrollPane1.setPreferredSize(new java.awt.Dimension(400, 95));

        jTableVehiculos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Placa", "Marca", "Tipo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableVehiculos);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 16;
        gridBagConstraints.gridwidth = 15;
        jPanelBuscar.add(jScrollPane1, gridBagConstraints);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Acciones"));
        jPanel3.setLayout(new java.awt.GridBagLayout());

        jButtonAsignarLugar.setText("Asignar lugar");
        jButtonAsignarLugar.setEnabled(false);
        jButtonAsignarLugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAsignarLugarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 9, 0);
        jPanel3.add(jButtonAsignarLugar, gridBagConstraints);

        jButton2.setText("Cerrar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 9, 0);
        jPanel3.add(jButton2, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 18;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 9, 0);
        jPanelBuscar.add(jPanel3, gridBagConstraints);

        jLabel1.setText("Nombre:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanelBuscar.add(jLabel1, gridBagConstraints);

        jLabel2.setText("Identificacion:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanelBuscar.add(jLabel2, gridBagConstraints);

        jLabel4.setText("Codigo Carnet:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanelBuscar.add(jLabel4, gridBagConstraints);

        jLabel5.setText("Genero:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanelBuscar.add(jLabel5, gridBagConstraints);

        jTextNombre.setEditable(false);
        jTextNombre.setMinimumSize(new java.awt.Dimension(150, 20));
        jTextNombre.setPreferredSize(new java.awt.Dimension(150, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanelBuscar.add(jTextNombre, gridBagConstraints);

        jTextId.setEditable(false);
        jTextId.setMinimumSize(new java.awt.Dimension(150, 20));
        jTextId.setPreferredSize(new java.awt.Dimension(150, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanelBuscar.add(jTextId, gridBagConstraints);

        jTextCarnet.setEditable(false);
        jTextCarnet.setMinimumSize(new java.awt.Dimension(150, 20));
        jTextCarnet.setPreferredSize(new java.awt.Dimension(150, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanelBuscar.add(jTextCarnet, gridBagConstraints);

        jTextGenero.setEditable(false);
        jTextGenero.setMinimumSize(new java.awt.Dimension(150, 20));
        jTextGenero.setPreferredSize(new java.awt.Dimension(150, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanelBuscar.add(jTextGenero, gridBagConstraints);

        jLabel6.setText("Vehiculos asociados:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 14;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanelBuscar.add(jLabel6, gridBagConstraints);

        jLabel7.setText("Rol: ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanelBuscar.add(jLabel7, gridBagConstraints);

        jTextRol.setEditable(false);
        jTextRol.setMinimumSize(new java.awt.Dimension(150, 20));
        jTextRol.setPreferredSize(new java.awt.Dimension(150, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanelBuscar.add(jTextRol, gridBagConstraints);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 649, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanelBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 649, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 350, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanelBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarActionPerformed
        limpiarTabla(jTableVehiculos);
        jButtonAsignarLugar.setEnabled(false);
        jTextNombre.setText("");
        jTextId.setText("");
        jTextCarnet.setText("");
        jTextGenero.setText("");
        jTextRol.setText("");
        if (jComboBoxCampoBusqueda.getSelectedItem().equals("Cedula"))
        {
            try {
                objCon = gestor.buscarConductorPorId(jtextCampoEscrituraBusqueda.getText());
                if(objCon!=null){
                    jTextNombre.setText(objCon.getNombres()+" "+objCon.getApellidos());
                    jTextId.setText(objCon.getId());
                    jTextCarnet.setText(objCon.getIdCarnet());
                    jTextGenero.setText(objCon.getGenero());
                    jTextRol.setText(objCon.getRol());
                    ArrayList<Vehiculo> vehiculos = objCon.getVehiculos();
                    DefaultTableModel model = (DefaultTableModel) jTableVehiculos.getModel();
                    for (int i = 0; i < vehiculos.size(); i++) {
                        Object fila[]={vehiculos.get(i).getPlaca(),vehiculos.get(i).getMarca(),vehiculos.get(i).getTipo()};
                        model.addRow(fila);

                    }
                    jButtonAsignarLugar.setEnabled(true);
                }

            } catch (ClassNotFoundException ex) {
                Logger.getLogger(GUIPrincipal.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
    }//GEN-LAST:event_jButtonBuscarActionPerformed

    private void jButtonAsignarLugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAsignarLugarActionPerformed
        System.out.println((String)jTableVehiculos.getModel().getValueAt(jTableVehiculos.getSelectedRow(),0));
        System.out.println((String)jTableVehiculos.getModel().getValueAt(jTableVehiculos.getSelectedRow(),1));
        System.out.println((String)jTableVehiculos.getModel().getValueAt(jTableVehiculos.getSelectedRow(),2));
        objMapa.setObjCon(objCon);
        Vehiculo veh = new Vehiculo();
        veh.setId(objCon.getId());
        veh.setIdCarnet(objCon.getIdCarnet());
        veh.setPlaca((String)jTableVehiculos.getModel().getValueAt(jTableVehiculos.getSelectedRow(),0));
        veh.setMarca((String)jTableVehiculos.getModel().getValueAt(jTableVehiculos.getSelectedRow(),1));
        veh.setTipo((String)jTableVehiculos.getModel().getValueAt(jTableVehiculos.getSelectedRow(),2));
        objMapa.setObjVeh(veh);
        objMapa.setVisible(true);
        JOptionPane.showMessageDialog(null, "Para asignar un lugar haga click donde desea estacionar");
    }//GEN-LAST:event_jButtonAsignarLugarActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.setVisible(false);

    }//GEN-LAST:event_jButton2ActionPerformed
    public void limpiarTabla(javax.swing.JTable tabla){
        try {
            DefaultTableModel modelo=(DefaultTableModel) tabla.getModel();
            int filas=tabla.getRowCount();
            for (int i = 0;i<filas; i++) {
                modelo.removeRow(0);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error al limpiar la tabla.");
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButtonAsignarLugar;
    private javax.swing.JButton jButtonBuscar;
    private javax.swing.JComboBox<String> jComboBoxCampoBusqueda;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanelBuscar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableVehiculos;
    private javax.swing.JTextField jTextCarnet;
    private javax.swing.JTextField jTextGenero;
    private javax.swing.JTextField jTextId;
    private javax.swing.JTextField jTextNombre;
    private javax.swing.JTextField jTextRol;
    private javax.swing.JTextField jtextCampoEscrituraBusqueda;
    // End of variables declaration//GEN-END:variables
}
