/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package parqueadero.presentacion;

import com.placeholder.PlaceHolder;
import static javax.swing.JOptionPane.showMessageDialog;
import mvcf.AModel;
import mvcf.AView;
import parqueadero.acceso.ServicioServidorCentralSocket;
import parqueadero.negocio.GestorAutenticacion;
import java.awt.*;


/**
 *
 * @author familia
 */
public class GUIIniciarSesion extends javax.swing.JFrame implements AView {

    //objetos
    private GUIPrincipal objPrincipal;
    private GestorAutenticacion objIniciarS;
    private GUIMenuAdministrador objGAdmin;
   
    public GUIIniciarSesion(GUIPrincipal pPrincipal, GUIMenuAdministrador pGp, GestorAutenticacion pGInicial) {
        objPrincipal = pPrincipal;
        objIniciarS = pGInicial;
        objGAdmin = pGp;
        
      
        //jPanelIniciar.setba
        initComponents();
        PlaceHolder ph = new PlaceHolder(jTextFieldUsu, "USUARIO");
        PlaceHolder ph2 = new PlaceHolder(jPasswordFieldContra, "CONTRASEÑA");
        ph.inicializar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanelIniciar = new javax.swing.JPanel();
        jTextFieldUsu = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jPasswordFieldContra = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de parqueo");
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMinimumSize(new java.awt.Dimension(400, 300));

        jPanelIniciar.setRequestFocusEnabled(false);
        java.awt.GridBagLayout jPanelIniciarLayout = new java.awt.GridBagLayout();
        jPanelIniciarLayout.columnWidths = new int[] {0, 11, 0, 11, 0, 11, 0, 11, 0};
        jPanelIniciarLayout.rowHeights = new int[] {0, 4, 0, 4, 0, 4, 0, 4, 0, 4, 0, 4, 0, 4, 0, 4, 0, 4, 0, 4, 0, 4, 0, 4, 0, 4, 0, 4, 0, 4, 0, 4, 0, 4, 0};
        jPanelIniciar.setLayout(jPanelIniciarLayout);

        jTextFieldUsu.setToolTipText("");
        jTextFieldUsu.setPreferredSize(new java.awt.Dimension(30, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 16;
        gridBagConstraints.ipadx = 53;
        gridBagConstraints.insets = new java.awt.Insets(220, 0, 0, 20);
        jPanelIniciar.add(jTextFieldUsu, gridBagConstraints);

        jButton2.setText("Aceptar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 22;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 20);
        jPanelIniciar.add(jButton2, gridBagConstraints);

        jPasswordFieldContra.setPreferredSize(new java.awt.Dimension(83, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 20;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 20);
        jPanelIniciar.add(jPasswordFieldContra, gridBagConstraints);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/parqueadero/imgs/unicauca.jpg"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.gridheight = 35;
        jPanelIniciar.add(jLabel5, gridBagConstraints);

        getContentPane().add(jPanelIniciar, java.awt.BorderLayout.CENTER);

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 11)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("BIENVENIDOS");
        getContentPane().add(jLabel1, java.awt.BorderLayout.PAGE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String bandera;
        String datos = jTextFieldUsu.getText()+","+jPasswordFieldContra.getText();
        bandera = objIniciarS.ValidarDatos(datos);
        if(bandera.equals("vigilante"))
        {
            this.setVisible(false);
            objPrincipal.setVisible(true);
        }
        else if (bandera.equals("administrador"))
        {
               this.setVisible(false);
               objGAdmin.setVisible(true);
        }
        else
        {
            showMessageDialog(null,"datos erroneos ó el usuario no se encuentra registrado");
            jPasswordFieldContra.setText("");
            jTextFieldUsu.setText("");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanelIniciar;
    private javax.swing.JPasswordField jPasswordFieldContra;
    private javax.swing.JTextField jTextFieldUsu;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actualizar(AModel amodel) {
        
    }
}
