/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package parqueadero.presentacion;

import java.awt.Color;
import java.beans.PropertyVetoException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import parqueadero.acceso.ServicioServidorCentralSocket;
import parqueadero.negocio.GestorPrincipal;
import parqueadero.negocio.Usuario;

/**
 *
 * @author admin
 */
public class GUIMenuAdministrador extends javax.swing.JFrame {

    /**
     * Creates new form GUIMenuAdministrador
     */
    private GestorPrincipal gp;
    private GUIIniciarSesion login;
    
    public GUIMenuAdministrador(GestorPrincipal pGP) {
        this.gp = pGP;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jInternalFrameAgregarVig = new javax.swing.JInternalFrame();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextNombres = new javax.swing.JTextField();
        jTextApellidos = new javax.swing.JTextField();
        jTextId = new javax.swing.JTextField();
        jTextContraseña = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextConfirmacionC = new javax.swing.JTextField();
        jButtonGuardar = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabelDatosObligatorios = new javax.swing.JLabel();
        jComboBoxUsuario = new javax.swing.JComboBox();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuRegistrar = new javax.swing.JMenuItem();
        jMenuItemCambiarUsu = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Administrador de Parqueadero");
        setMinimumSize(new java.awt.Dimension(700, 456));
        setPreferredSize(new java.awt.Dimension(700, 456));

        jDesktopPane1.setMinimumSize(new java.awt.Dimension(700, 456));
        jDesktopPane1.setLayout(new java.awt.BorderLayout());

        jInternalFrameAgregarVig.setMinimumSize(new java.awt.Dimension(589, 356));
        jInternalFrameAgregarVig.setVisible(false);

        jPanel1.setLayout(new java.awt.GridBagLayout());

        jLabel1.setText("Por favor Introduzca los datos del usuario a registrar:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 23, 0, 0);
        jPanel1.add(jLabel1, gridBagConstraints);

        jLabel2.setText("*Nombres:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(33, 89, 0, 0);
        jPanel1.add(jLabel2, gridBagConstraints);

        jLabel3.setText("*Apellidos:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(21, 89, 0, 0);
        jPanel1.add(jLabel3, gridBagConstraints);

        jLabel4.setText("*Identificacion:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(21, 89, 0, 0);
        jPanel1.add(jLabel4, gridBagConstraints);

        jLabel5.setText("*Rol:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(22, 89, 0, 0);
        jPanel1.add(jLabel5, gridBagConstraints);

        jLabel6.setText("*Contraseña:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(21, 89, 0, 0);
        jPanel1.add(jLabel6, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 139;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(30, 4, 0, 0);
        jPanel1.add(jTextNombres, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 139;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 4, 0, 0);
        jPanel1.add(jTextApellidos, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.ipadx = 139;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 4, 0, 0);
        jPanel1.add(jTextId, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 139;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 4, 0, 0);
        jPanel1.add(jTextContraseña, gridBagConstraints);

        jLabel7.setText("*Confirmar Contraseña:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 13;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(21, 89, 0, 0);
        jPanel1.add(jLabel7, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 13;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 139;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 4, 40, 0);
        jPanel1.add(jTextConfirmacionC, gridBagConstraints);

        jButtonGuardar.setText("Guardar");
        jButtonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuardarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 40, 0, 0);
        jPanel1.add(jButtonGuardar, gridBagConstraints);

        jButton2.setText("Cancelar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 40, 0, 63);
        jPanel1.add(jButton2, gridBagConstraints);

        jLabelDatosObligatorios.setText("\"Los datos marcados con \"*\" son obligatorios\".");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 15;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel1.add(jLabelDatosObligatorios, gridBagConstraints);

        jComboBoxUsuario.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "administrador", "vigilante" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LAST_LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(0, 4, 0, 0);
        jPanel1.add(jComboBoxUsuario, gridBagConstraints);

        jInternalFrameAgregarVig.getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        jDesktopPane1.add(jInternalFrameAgregarVig, java.awt.BorderLayout.CENTER);

        getContentPane().add(jDesktopPane1, java.awt.BorderLayout.CENTER);

        jMenu1.setText("Opciones");

        jMenuRegistrar.setText("Registrar Usuario");
        jMenuRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuRegistrarActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuRegistrar);

        jMenuItemCambiarUsu.setText("Cambiar de Rol");
        jMenuItemCambiarUsu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCambiarUsuActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemCambiarUsu);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Ayuda");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuRegistrarActionPerformed
        
        try {
            jInternalFrameAgregarVig.setMaximum(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(GUIMenuAdministrador.class.getName()).log(Level.SEVERE, null, ex);
        }
        jInternalFrameAgregarVig.setVisible(true);
    }//GEN-LAST:event_jMenuRegistrarActionPerformed

    private void jButtonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGuardarActionPerformed
       if(validarDatos()){
       Usuario  usu = new Usuario();
       usu.setNombres(jTextNombres.getText());
       usu.setApellidos(jTextApellidos.getText());
       usu.setId(jTextId.getText());
       usu.setRol(jComboBoxUsuario.getSelectedItem().toString());
       usu.setContraseña(jTextContraseña.getText());
        if(gp.agregarUsuario(usu))
            {
                JOptionPane.showMessageDialog(null, "Agregado Correctamente");
                limpiarCajas(true); 
                
            }
            else
            JOptionPane.showMessageDialog(null, "No fue posible agregar al usuario");
       }
    
           
    }//GEN-LAST:event_jButtonGuardarActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        jInternalFrameAgregarVig.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jMenuItemCambiarUsuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCambiarUsuActionPerformed
        this.setVisible(false);
        login.setVisible(true);
        
    }//GEN-LAST:event_jMenuItemCambiarUsuActionPerformed

    /**
     * @param args the command line arguments
     */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButtonGuardar;
    private javax.swing.JComboBox jComboBoxUsuario;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JInternalFrame jInternalFrameAgregarVig;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabelDatosObligatorios;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItemCambiarUsu;
    private javax.swing.JMenuItem jMenuRegistrar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextApellidos;
    private javax.swing.JTextField jTextConfirmacionC;
    private javax.swing.JTextField jTextContraseña;
    private javax.swing.JTextField jTextId;
    private javax.swing.JTextField jTextNombres;
    // End of variables declaration//GEN-END:variables

public boolean validarDatos()
    {
        
        if("".equals(jTextId.getText().toString()) ||  "".equals(jTextNombres.getText()) || "".equals(jTextApellidos.getText()) ||  "".equals(jTextContraseña.getText())|| "".equals(jTextConfirmacionC.getText()))
        {
            jLabelDatosObligatorios.setForeground(Color.red);
            return false;          
        }
        
        if(!jTextContraseña.getText().equals(jTextConfirmacionC.getText()))
        {
            JOptionPane.showMessageDialog(null,"las contraseñas no coiciden");
            jTextContraseña.setText("");
            jTextConfirmacionC.setText("");
            return false;
        }
        
        
        
        return true;
    }
 public void limpiarCajas(boolean todas) {
        if (todas) {
        }
        
        jTextId.setText("");
        jTextNombres.setText("");
        jTextApellidos.setText("");
        jTextContraseña.setText("");
        jTextConfirmacionC.setText("");
    }

    public void setLogin(GUIIniciarSesion login) {
        this.login = login;
    }
}
