/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package parqueadero.presentacion;
import java.awt.Color;
import java.beans.PropertyVetoException;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.plaf.TableUI;
import javax.swing.table.DefaultTableModel;
import mvcf.*;
import parqueadero.negocio.Conductor;
import parqueadero.negocio.GestionMapa;
import parqueadero.negocio.GestorPrincipal;
import parqueadero.negocio.LugarMapa;
import parqueadero.negocio.Multa;
import parqueadero.negocio.Vehiculo;

/**
 *
 * @author Emmanuel
 */
public class GUIPrincipal extends javax.swing.JFrame implements AView {

    /**
     * Creates new form GUIBuscarConductor
     */
    
    private GestorPrincipal gestor;
    private MapaParqueadero objMapa;
    private GUIRegistrarCon objRegistarCon;
    private GUIRegistrarVeh objGUIRegistrarVeh;
    
    private GUIIniciarSesion login;
    public GUIPrincipal(MapaParqueadero mapa, GestorPrincipal pGprincipal) {
        initComponents();
        
       
        gestor = pGprincipal;
        objMapa = mapa;
      
        //jDesktopPaneRegistro.add(objRegistarCon);
    }

    public void setLogin(GUIIniciarSesion login) {
        this.login = login;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenuItemBuscarC = new javax.swing.JMenuItem();
        jMenuAgregar = new javax.swing.JMenuItem();
        jMenuAgregarV = new javax.swing.JMenuItem();
        jMenuItemMulta = new javax.swing.JMenuItem();
        jMenuItemCambiarUsu = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuMapa = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Vigilante de Parqueadero");
        setMinimumSize(new java.awt.Dimension(700, 600));
        setPreferredSize(new java.awt.Dimension(700, 600));

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 660, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 383, Short.MAX_VALUE)
        );

        getContentPane().add(jDesktopPane1, java.awt.BorderLayout.CENTER);

        jMenu3.setText("Opciones");

        jMenuItemBuscarC.setText("Buscar Conductor");
        jMenuItemBuscarC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemBuscarCActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItemBuscarC);

        jMenuAgregar.setText("Agregar Conductor");
        jMenuAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuAgregarActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuAgregar);

        jMenuAgregarV.setText("Agregar Vehiculo");
        jMenuAgregarV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuAgregarVActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuAgregarV);

        jMenuItemMulta.setText("Agregar Multa");
        jMenuItemMulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemMultaActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItemMulta);

        jMenuItemCambiarUsu.setText("Cambiar de Rol");
        jMenuItemCambiarUsu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCambiarUsuActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItemCambiarUsu);

        jMenuBar2.add(jMenu3);

        jMenu4.setText("Mapa");

        jMenuMapa.setText("Liberar Lugar (Mapa)");
        jMenuMapa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuMapaActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuMapa);

        jMenuItem1.setText("Mostrar Mapa");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem1);

        jMenuBar2.add(jMenu4);

        setJMenuBar(jMenuBar2);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuAgregarActionPerformed
                
        //objRegistarCon.setVisible(true);
        GUIRegistrarConductor rConductor = new GUIRegistrarConductor(gestor);
        jDesktopPane1.removeAll();
        jDesktopPane1.repaint();
        jDesktopPane1.add(rConductor);
        try {
            rConductor.setMaximum(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(GUIPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
        rConductor.show();
        
        
    }//GEN-LAST:event_jMenuAgregarActionPerformed

    private void jMenuMapaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuMapaActionPerformed
       String placa = JOptionPane.showInputDialog("Digite la placa del vehiculo:");
        LugarMapa lugar = GestionMapa.liberarLugar(placa);
        if(lugar!=null)
        {
            System.out.println("aqui entro");
            lugar.getLugar().setBackground(Color.green);
            JOptionPane.showMessageDialog(null, "lugar liberado");
        }
        else
            JOptionPane.showMessageDialog(null, "La placa que introdujo no tiene un lugar asignado");
                                 
    }//GEN-LAST:event_jMenuMapaActionPerformed

    private void jMenuAgregarVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuAgregarVActionPerformed
        GUIRegistrarVeh rVeh = new GUIRegistrarVeh(gestor);
        jDesktopPane1.removeAll();
        jDesktopPane1.repaint();
        jDesktopPane1.add(rVeh);
        try {
            rVeh.setMaximum(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(GUIPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
        rVeh.show();
        
        
    }//GEN-LAST:event_jMenuAgregarVActionPerformed

    private void jMenuItemBuscarCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemBuscarCActionPerformed
       jDesktopPane1.removeAll();
       jDesktopPane1.repaint();
       GUIBuscarConductor buscar = new GUIBuscarConductor(gestor, objMapa);
        jDesktopPane1.add(buscar);
        try {
            buscar.setMaximum(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(GUIPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
        buscar.show();
                
    }//GEN-LAST:event_jMenuItemBuscarCActionPerformed

    private void jMenuItemCambiarUsuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCambiarUsuActionPerformed
        this.setVisible(false);
        login.setVisible(true);
    }//GEN-LAST:event_jMenuItemCambiarUsuActionPerformed

    private void jMenuItemMultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemMultaActionPerformed
        jDesktopPane1.removeAll();
        jDesktopPane1.repaint();
        GUIMulta multa = new GUIMulta(gestor);
        jDesktopPane1.add(multa);
        try {
            multa.setMaximum(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(GUIPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
        multa.show();
        
    }//GEN-LAST:event_jMenuItemMultaActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        objMapa.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed
    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuItem jMenuAgregar;
    private javax.swing.JMenuItem jMenuAgregarV;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItemBuscarC;
    private javax.swing.JMenuItem jMenuItemCambiarUsu;
    private javax.swing.JMenuItem jMenuItemMulta;
    private javax.swing.JMenuItem jMenuMapa;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actualizar(AModel amodel) {
    }
    
    
}
