/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package parqueadero.presentacion;

import java.awt.Color;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import parqueadero.negocio.Conductor;
import parqueadero.negocio.GestorPrincipal;
import parqueadero.negocio.Vehiculo;


/**
 *
 * @author familia
 */
public class GUIRegistrarVeh extends javax.swing.JInternalFrame {

    private GestorPrincipal objGestorP;
    
    public GUIRegistrarVeh(GestorPrincipal pGestor) {
        
        initComponents();
        objGestorP = pGestor;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jButtonReg = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jComboBoxTipo = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextMarca = new javax.swing.JTextField();
        jTextId = new javax.swing.JTextField();
        jTextPlaca = new javax.swing.JTextField();
        jLabelDatosObligatorios = new javax.swing.JLabel();
        jLabelCarnet = new javax.swing.JLabel();
        jTextCarnet = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldNombre = new javax.swing.JTextField();

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jLabel4.setText("Acciones");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(1, 11, 0, 0);
        jPanel1.add(jLabel4, gridBagConstraints);

        jButtonReg.setText("Registar");
        jButtonReg.setEnabled(false);
        jButtonReg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(28, 81, 36, 0);
        jPanel1.add(jButtonReg, gridBagConstraints);

        jButton2.setText("Cerrar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(28, 45, 36, 100);
        jPanel1.add(jButton2, gridBagConstraints);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_END);

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        java.awt.GridBagLayout jPanel2Layout = new java.awt.GridBagLayout();
        jPanel2Layout.columnWidths = new int[] {0, 8, 0, 8, 0, 8, 0, 8, 0, 8, 0};
        jPanel2Layout.rowHeights = new int[] {0, 4, 0, 4, 0, 4, 0, 4, 0, 4, 0, 4, 0, 4, 0};
        jPanel2.setLayout(jPanel2Layout);

        jLabel1.setText("*N. Placa:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(30, 50, 0, 0);
        jPanel2.add(jLabel1, gridBagConstraints);

        jLabel3.setText("*Tipo:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(30, 50, 16, 0);
        jPanel2.add(jLabel3, gridBagConstraints);

        jLabel5.setText("*Id Conductor:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(35, 50, 0, 0);
        jPanel2.add(jLabel5, gridBagConstraints);

        jComboBoxTipo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Carro", "Moto" }));
        jComboBoxTipo.setPreferredSize(new java.awt.Dimension(70, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(30, 43, 16, 53);
        jPanel2.add(jComboBoxTipo, gridBagConstraints);

        jLabel2.setText("Datos del Vehiculo:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 7);
        jPanel2.add(jLabel2, gridBagConstraints);

        jLabel6.setText("*Marca:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(30, 50, 0, 0);
        jPanel2.add(jLabel6, gridBagConstraints);

        jTextMarca.setMinimumSize(new java.awt.Dimension(200, 20));
        jTextMarca.setPreferredSize(new java.awt.Dimension(200, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.insets = new java.awt.Insets(30, 43, 0, 10);
        jPanel2.add(jTextMarca, gridBagConstraints);

        jTextId.setMinimumSize(new java.awt.Dimension(200, 20));
        jTextId.setPreferredSize(new java.awt.Dimension(200, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(30, 43, 0, 10);
        jPanel2.add(jTextId, gridBagConstraints);

        jTextPlaca.setMinimumSize(new java.awt.Dimension(200, 20));
        jTextPlaca.setPreferredSize(new java.awt.Dimension(200, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.insets = new java.awt.Insets(30, 43, 0, 10);
        jPanel2.add(jTextPlaca, gridBagConstraints);

        jLabelDatosObligatorios.setText("\"Los datos marcados con \"*\" son obligatorios\".");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 14;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel2.add(jLabelDatosObligatorios, gridBagConstraints);

        jLabelCarnet.setText("*Codigo Carnet:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(35, 50, 0, 0);
        jPanel2.add(jLabelCarnet, gridBagConstraints);

        jTextCarnet.setEditable(false);
        jTextCarnet.setMinimumSize(new java.awt.Dimension(200, 20));
        jTextCarnet.setPreferredSize(new java.awt.Dimension(200, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(30, 43, 0, 10);
        jPanel2.add(jTextCarnet, gridBagConstraints);

        jButton3.setText("buscar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 10;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LAST_LINE_END;
        jPanel2.add(jButton3, gridBagConstraints);

        jLabel7.setText("*Nombre Conductor:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.insets = new java.awt.Insets(35, 50, 0, 0);
        jPanel2.add(jLabel7, gridBagConstraints);

        jTextFieldNombre.setEditable(false);
        jTextFieldNombre.setMinimumSize(new java.awt.Dimension(200, 20));
        jTextFieldNombre.setPreferredSize(new java.awt.Dimension(200, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.insets = new java.awt.Insets(30, 43, 0, 10);
        jPanel2.add(jTextFieldNombre, gridBagConstraints);

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonRegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegActionPerformed
        jLabelDatosObligatorios.setForeground(Color.red);
        if(validarDatos()){
            
            Vehiculo objVeh = new Vehiculo(jTextId.getText(),jTextPlaca.getText(),jComboBoxTipo.getSelectedItem().toString(),jTextCarnet.getText(),jTextMarca.getText());
            if(objGestorP.agregarVehiculoAConductor(objVeh))
            {
                JOptionPane.showMessageDialog(null, "Agregado Correctamente");
                limpiarCajas(true); 
                this.setVisible(false);
            }
            else
            JOptionPane.showMessageDialog(null, "No fue posible agregar al conductor");
        }
    }//GEN-LAST:event_jButtonRegActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try {
            Conductor con = objGestorP.buscarConductorPorId(jTextId.getText());
            if(con!=null)
            {
                jTextId.setEditable(false);
                jTextCarnet.setText(con.getIdCarnet());
                jTextFieldNombre.setText(con.getNombres()+" "+ con.getApellidos());
                jButtonReg.setEnabled(true);
            }
            else
                JOptionPane.showMessageDialog(null, "Conductor no encontrado");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(GUIRegistrarVeh.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton3ActionPerformed
    public boolean validarDatos()
    {
        
        if("".equals(jTextId.getText().toString()) || "".equals(jTextCarnet.getText()) || "".equals(jTextMarca.getText()) || "".equals(jTextPlaca.getText()))
        {
            jLabelDatosObligatorios.setForeground(Color.red);
            return false;          
        }
        
        
        
        return true;
    }
    
    public void limpiarCajas(boolean todas) {
        if (todas) {
        }
        
        jTextId.setText("");
        jTextCarnet.setText("");
        jTextMarca.setText("");
        jTextPlaca.setText("");
        jComboBoxTipo.setSelectedIndex(0);
    }
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButtonReg;
    private javax.swing.JComboBox jComboBoxTipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabelCarnet;
    private javax.swing.JLabel jLabelDatosObligatorios;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextCarnet;
    private javax.swing.JTextField jTextFieldNombre;
    private javax.swing.JTextField jTextId;
    private javax.swing.JTextField jTextMarca;
    private javax.swing.JTextField jTextPlaca;
    // End of variables declaration//GEN-END:variables
}
