/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package parqueadero.presentacion;

import java.awt.Color;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import parqueadero.negocio.Conductor;
import parqueadero.negocio.GestorPrincipal;

/**
 *
 * @author familia
 */
public class GUIRegistrarCon extends javax.swing.JDialog {

    //objetos 
    
    private GestorPrincipal objGestorP;
    
    
    public GUIRegistrarCon(java.awt.Frame parent, boolean modal, GestorPrincipal pGPrincipal) {
        super(parent, modal);
        initComponents();
        objGestorP = pGPrincipal;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jInternalFrame1 = new javax.swing.JInternalFrame();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jComboBoxGenero = new javax.swing.JComboBox();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jTextNombres = new javax.swing.JTextField();
        jTextApellidos = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jButtonGuardar = new javax.swing.JButton();
        jButtonCerrar = new javax.swing.JButton();
        jLabelDatosObligatorios = new javax.swing.JLabel();
        jComboBoxRol = new javax.swing.JComboBox();
        jTextId = new javax.swing.JTextField();
        jTextIdCarnet = new javax.swing.JTextField();
        rSDateFechaNac = new rojeru_san.componentes.RSDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jInternalFrame1.setTitle("Registrar Conductor\n");
        jInternalFrame1.setPreferredSize(new java.awt.Dimension(600, 500));
        jInternalFrame1.setVisible(true);

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.setLayout(new java.awt.GridBagLayout());

        jLabel3.setText("*Apellidos:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 30, 0, 0);
        jPanel3.add(jLabel3, gridBagConstraints);

        jLabel2.setText("*Nombres: ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 30, 0, 0);
        jPanel3.add(jLabel2, gridBagConstraints);

        jLabel1.setText("Datos del Conductor:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 33, 0, 0);
        jPanel3.add(jLabel1, gridBagConstraints);

        jLabel5.setText("*Fecha de Nacimiento:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 30, 0, 0);
        jPanel3.add(jLabel5, gridBagConstraints);

        jLabel6.setText("*Rol:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 30, 0, 0);
        jPanel3.add(jLabel6, gridBagConstraints);

        jLabel4.setText("*Genero:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(26, 30, 13, 0);
        jPanel3.add(jLabel4, gridBagConstraints);

        jComboBoxGenero.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Masculino", "Femenino" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(26, 21, 13, 74);
        jPanel3.add(jComboBoxGenero, gridBagConstraints);

        jLabel11.setText("*Identificacion:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(20, 30, 0, 0);
        jPanel3.add(jLabel11, gridBagConstraints);

        jLabel12.setText("*Codigo Carnet:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.insets = new java.awt.Insets(20, 30, 0, 0);
        jPanel3.add(jLabel12, gridBagConstraints);

        jTextNombres.setMinimumSize(new java.awt.Dimension(210, 27));
        jTextNombres.setPreferredSize(new java.awt.Dimension(210, 27));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 21, 0, 74);
        jPanel3.add(jTextNombres, gridBagConstraints);

        jTextApellidos.setMinimumSize(new java.awt.Dimension(210, 27));
        jTextApellidos.setPreferredSize(new java.awt.Dimension(210, 27));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 21, 0, 74);
        jPanel3.add(jTextApellidos, gridBagConstraints);

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setLayout(new java.awt.GridBagLayout());

        jLabel7.setText("Acciones");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 11, 0, 0);
        jPanel2.add(jLabel7, gridBagConstraints);

        jButtonGuardar.setText("Guardar");
        jButtonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuardarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 92, 35, 0);
        jPanel2.add(jButtonGuardar, gridBagConstraints);

        jButtonCerrar.setText("Cerrar");
        jButtonCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCerrarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 50, 35, 169);
        jPanel2.add(jButtonCerrar, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.gridwidth = 7;
        jPanel3.add(jPanel2, gridBagConstraints);

        jLabelDatosObligatorios.setText("\"Los datos marcados con \"*\" son obligatorios\".");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel3.add(jLabelDatosObligatorios, gridBagConstraints);

        jComboBoxRol.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Estudiante", "Docente", "Administrativo" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(20, 21, 0, 74);
        jPanel3.add(jComboBoxRol, gridBagConstraints);

        jTextId.setMinimumSize(new java.awt.Dimension(210, 27));
        jTextId.setPreferredSize(new java.awt.Dimension(210, 27));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 21, 0, 74);
        jPanel3.add(jTextId, gridBagConstraints);

        jTextIdCarnet.setMinimumSize(new java.awt.Dimension(210, 27));
        jTextIdCarnet.setPreferredSize(new java.awt.Dimension(210, 27));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(20, 21, 0, 74);
        jPanel3.add(jTextIdCarnet, gridBagConstraints);

        rSDateFechaNac.setFormatoFecha("dd/MM/yyyy");
        rSDateFechaNac.setMinimumSize(new java.awt.Dimension(240, 40));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.insets = new java.awt.Insets(12, 0, 0, 24);
        jPanel3.add(rSDateFechaNac, gridBagConstraints);

        jInternalFrame1.getContentPane().add(jPanel3, java.awt.BorderLayout.CENTER);

        getContentPane().add(jInternalFrame1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGuardarActionPerformed
        jLabelDatosObligatorios.setForeground(Color.red);
        if(validarDatos()){
            SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
          
            String fecha =  sdf.format(rSDateFechaNac.getDatoFecha());
            Conductor objCon = new Conductor(jTextId.getText(),jTextIdCarnet.getText(),jTextNombres.getText(),jTextApellidos.getText(),jComboBoxRol.getSelectedItem().toString(),jComboBoxGenero.getSelectedItem().toString(),fecha);
            if(objGestorP.agregarConductor(objCon))
            {
                JOptionPane.showMessageDialog(null, "Agregado Correctamente");
                limpiarCajas(true); 
                this.setVisible(false);
            }
            else
            JOptionPane.showMessageDialog(null, "No fue posible agregar al conductor");
        }
    }//GEN-LAST:event_jButtonGuardarActionPerformed

    private void jButtonCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCerrarActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_jButtonCerrarActionPerformed
    
    
    public boolean validarDatos()
    {
        
        if("".equals(jTextId.getText().toString()) || "".equals(jTextIdCarnet.getText()) || "".equals(jTextNombres.getText()) || "".equals(jTextApellidos.getText()) || rSDateFechaNac.getDatoFecha() == null)
        {
            jLabelDatosObligatorios.setForeground(Color.red);
            return false;          
        }
        
        return true;
    }
    
 
    
    public boolean isNumeric(String cadena) {

        boolean resultado;

        try {
            Integer.parseInt(cadena);
            resultado = true;
        } catch (NumberFormatException excepcion) {
            resultado = false;
        }

        return resultado;
    }

    public void limpiarCajas(boolean todas) {
        if (todas) {
        }
        
        jTextId.setText("");
        jTextIdCarnet.setText("");
        jTextNombres.setText("");
        jTextApellidos.setText("");
        jComboBoxRol.setSelectedIndex(0);
        jComboBoxGenero.setSelectedIndex(0);
    }
    /**
     * @param args the command line arguments
     */
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCerrar;
    private javax.swing.JButton jButtonGuardar;
    private javax.swing.JComboBox jComboBoxGenero;
    private javax.swing.JComboBox jComboBoxRol;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabelDatosObligatorios;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jTextApellidos;
    private javax.swing.JTextField jTextId;
    private javax.swing.JTextField jTextIdCarnet;
    private javax.swing.JTextField jTextNombres;
    private rojeru_san.componentes.RSDateChooser rSDateFechaNac;
    // End of variables declaration//GEN-END:variables


}
