/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package parqueadero.presentacion;

import java.awt.Color;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.border.Border;
import parqueadero.negocio.Conductor;
import parqueadero.negocio.GestionMapa;
import parqueadero.negocio.LugarMapa;
import parqueadero.negocio.Vehiculo;

/**
 *
 * @author INGESIS
 */
public class MapaParqueadero extends javax.swing.JFrame {

    private GestionMapa gMapa;
    private GUIPrincipal principal;
    private Conductor objCon;
    private Vehiculo objVeh;
    /**
     * Creates new form MapaParqueadero
     */
    public MapaParqueadero() {
        initComponents();
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        gMapa = new GestionMapa();
        
       
    }

    public GUIPrincipal getPrincipal() {
        return principal;
    }

    public void setPrincipal(GUIPrincipal principal) {
        this.principal = principal;
    }

    public Conductor getObjCon() {
        return objCon;
    }

    public void setObjCon(Conductor objCon) {
        this.objCon = objCon;
    }

    public Vehiculo getObjVeh() {
        return objVeh;
    }

    public void setObjVeh(Vehiculo objVeh) {
        this.objVeh = objVeh;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanelPuesto20 = new javax.swing.JPanel();
        jPanelPuesto21 = new javax.swing.JPanel();
        jPanelPuesto23 = new javax.swing.JPanel();
        jPanelPuesto24 = new javax.swing.JPanel();
        jPanelPuesto29 = new javax.swing.JPanel();
        jPanelPuesto25 = new javax.swing.JPanel();
        jPanelPuesto30 = new javax.swing.JPanel();
        jPanelPuesto26 = new javax.swing.JPanel();
        jPanelPuesto31 = new javax.swing.JPanel();
        jPanelPuesto27 = new javax.swing.JPanel();
        jPanelPuesto22 = new javax.swing.JPanel();
        jPanelPuesto28 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel28 = new javax.swing.JPanel();
        jPanelPuesto7 = new javax.swing.JPanel();
        jPanelPuesto10 = new javax.swing.JPanel();
        jPanelPuesto5 = new javax.swing.JPanel();
        jPanel32 = new javax.swing.JPanel();
        jPanelPuesto3 = new javax.swing.JPanel();
        jPanelPuesto1 = new javax.swing.JPanel();
        jPanelPuesto8 = new javax.swing.JPanel();
        jPanelPuesto2 = new javax.swing.JPanel();
        jPanelPuesto9 = new javax.swing.JPanel();
        jPanelPuesto6 = new javax.swing.JPanel();
        jPanelPuesto4 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        jPanel52 = new javax.swing.JPanel();
        jPanel53 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanelPuesto17 = new javax.swing.JPanel();
        jPanelPuesto18 = new javax.swing.JPanel();
        jPanelPuesto14 = new javax.swing.JPanel();
        jPanelPuesto15 = new javax.swing.JPanel();
        jPanelPuesto16 = new javax.swing.JPanel();
        jPanelPuesto11 = new javax.swing.JPanel();
        jPanelPuesto12 = new javax.swing.JPanel();
        jPanelPuesto19 = new javax.swing.JPanel();
        jPanelPuesto13 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButtonCerrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Mapa parqueadero");
        setPreferredSize(new java.awt.Dimension(800, 700));

        jPanel1.setEnabled(false);
        jPanel1.setMinimumSize(new java.awt.Dimension(800, 400));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 400));
        java.awt.GridBagLayout jPanel1Layout = new java.awt.GridBagLayout();
        jPanel1Layout.columnWidths = new int[] {0, 11, 0, 11, 0, 11, 0, 11, 0, 11, 0, 11, 0, 11, 0};
        jPanel1Layout.rowHeights = new int[] {0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0};
        jPanel1.setLayout(jPanel1Layout);

        jPanel5.setEnabled(false);
        jPanel5.setMinimumSize(new java.awt.Dimension(150, 150));
        jPanel5.setPreferredSize(new java.awt.Dimension(150, 150));
        java.awt.GridBagLayout jPanel5Layout = new java.awt.GridBagLayout();
        jPanel5Layout.columnWidths = new int[] {0, 9, 0, 9, 0, 9, 0, 9, 0, 9, 0, 9, 0, 9, 0, 9, 0};
        jPanel5Layout.rowHeights = new int[] {0, 4, 0, 4, 0, 4, 0, 4, 0, 4, 0, 4, 0, 4, 0, 4, 0};
        jPanel5.setLayout(jPanel5Layout);

        jPanelPuesto20.setBackground(new java.awt.Color(0, 204, 51));
        jPanelPuesto20.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanelPuesto20.setMaximumSize(new java.awt.Dimension(20, 20));
        jPanelPuesto20.setMinimumSize(new java.awt.Dimension(20, 20));

        javax.swing.GroupLayout jPanelPuesto20Layout = new javax.swing.GroupLayout(jPanelPuesto20);
        jPanelPuesto20.setLayout(jPanelPuesto20Layout);
        jPanelPuesto20Layout.setHorizontalGroup(
            jPanelPuesto20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 14, Short.MAX_VALUE)
        );
        jPanelPuesto20Layout.setVerticalGroup(
            jPanelPuesto20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 14, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel5.add(jPanelPuesto20, gridBagConstraints);

        jPanelPuesto21.setBackground(new java.awt.Color(0, 204, 51));
        jPanelPuesto21.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanelPuesto21.setMaximumSize(new java.awt.Dimension(20, 20));
        jPanelPuesto21.setMinimumSize(new java.awt.Dimension(20, 20));

        javax.swing.GroupLayout jPanelPuesto21Layout = new javax.swing.GroupLayout(jPanelPuesto21);
        jPanelPuesto21.setLayout(jPanelPuesto21Layout);
        jPanelPuesto21Layout.setHorizontalGroup(
            jPanelPuesto21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 14, Short.MAX_VALUE)
        );
        jPanelPuesto21Layout.setVerticalGroup(
            jPanelPuesto21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 14, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 0;
        jPanel5.add(jPanelPuesto21, gridBagConstraints);

        jPanelPuesto23.setBackground(new java.awt.Color(0, 204, 51));
        jPanelPuesto23.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanelPuesto23.setMaximumSize(new java.awt.Dimension(20, 20));
        jPanelPuesto23.setMinimumSize(new java.awt.Dimension(20, 20));

        javax.swing.GroupLayout jPanelPuesto23Layout = new javax.swing.GroupLayout(jPanelPuesto23);
        jPanelPuesto23.setLayout(jPanelPuesto23Layout);
        jPanelPuesto23Layout.setHorizontalGroup(
            jPanelPuesto23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 14, Short.MAX_VALUE)
        );
        jPanelPuesto23Layout.setVerticalGroup(
            jPanelPuesto23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 14, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        jPanel5.add(jPanelPuesto23, gridBagConstraints);

        jPanelPuesto24.setBackground(new java.awt.Color(0, 204, 51));
        jPanelPuesto24.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanelPuesto24.setMaximumSize(new java.awt.Dimension(20, 20));
        jPanelPuesto24.setMinimumSize(new java.awt.Dimension(20, 20));

        javax.swing.GroupLayout jPanelPuesto24Layout = new javax.swing.GroupLayout(jPanelPuesto24);
        jPanelPuesto24.setLayout(jPanelPuesto24Layout);
        jPanelPuesto24Layout.setHorizontalGroup(
            jPanelPuesto24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 14, Short.MAX_VALUE)
        );
        jPanelPuesto24Layout.setVerticalGroup(
            jPanelPuesto24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 14, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel5.add(jPanelPuesto24, gridBagConstraints);

        jPanelPuesto29.setBackground(new java.awt.Color(0, 204, 51));
        jPanelPuesto29.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanelPuesto29.setMaximumSize(new java.awt.Dimension(20, 20));
        jPanelPuesto29.setMinimumSize(new java.awt.Dimension(20, 20));

        javax.swing.GroupLayout jPanelPuesto29Layout = new javax.swing.GroupLayout(jPanelPuesto29);
        jPanelPuesto29.setLayout(jPanelPuesto29Layout);
        jPanelPuesto29Layout.setHorizontalGroup(
            jPanelPuesto29Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 14, Short.MAX_VALUE)
        );
        jPanelPuesto29Layout.setVerticalGroup(
            jPanelPuesto29Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 14, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 16;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel5.add(jPanelPuesto29, gridBagConstraints);

        jPanelPuesto25.setBackground(new java.awt.Color(0, 204, 51));
        jPanelPuesto25.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanelPuesto25.setMaximumSize(new java.awt.Dimension(20, 20));
        jPanelPuesto25.setMinimumSize(new java.awt.Dimension(20, 20));

        javax.swing.GroupLayout jPanelPuesto25Layout = new javax.swing.GroupLayout(jPanelPuesto25);
        jPanelPuesto25.setLayout(jPanelPuesto25Layout);
        jPanelPuesto25Layout.setHorizontalGroup(
            jPanelPuesto25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 14, Short.MAX_VALUE)
        );
        jPanelPuesto25Layout.setVerticalGroup(
            jPanelPuesto25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 14, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 16;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel5.add(jPanelPuesto25, gridBagConstraints);

        jPanelPuesto30.setBackground(new java.awt.Color(0, 204, 51));
        jPanelPuesto30.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanelPuesto30.setMaximumSize(new java.awt.Dimension(20, 20));
        jPanelPuesto30.setMinimumSize(new java.awt.Dimension(20, 20));

        javax.swing.GroupLayout jPanelPuesto30Layout = new javax.swing.GroupLayout(jPanelPuesto30);
        jPanelPuesto30.setLayout(jPanelPuesto30Layout);
        jPanelPuesto30Layout.setHorizontalGroup(
            jPanelPuesto30Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 14, Short.MAX_VALUE)
        );
        jPanelPuesto30Layout.setVerticalGroup(
            jPanelPuesto30Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 14, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 16;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel5.add(jPanelPuesto30, gridBagConstraints);

        jPanelPuesto26.setBackground(new java.awt.Color(0, 204, 51));
        jPanelPuesto26.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanelPuesto26.setMaximumSize(new java.awt.Dimension(20, 20));
        jPanelPuesto26.setMinimumSize(new java.awt.Dimension(20, 20));

        javax.swing.GroupLayout jPanelPuesto26Layout = new javax.swing.GroupLayout(jPanelPuesto26);
        jPanelPuesto26.setLayout(jPanelPuesto26Layout);
        jPanelPuesto26Layout.setHorizontalGroup(
            jPanelPuesto26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 14, Short.MAX_VALUE)
        );
        jPanelPuesto26Layout.setVerticalGroup(
            jPanelPuesto26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 14, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.insets = new java.awt.Insets(23, 0, 0, 0);
        jPanel5.add(jPanelPuesto26, gridBagConstraints);

        jPanelPuesto31.setBackground(new java.awt.Color(0, 204, 51));
        jPanelPuesto31.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanelPuesto31.setMaximumSize(new java.awt.Dimension(20, 20));
        jPanelPuesto31.setMinimumSize(new java.awt.Dimension(20, 20));

        javax.swing.GroupLayout jPanelPuesto31Layout = new javax.swing.GroupLayout(jPanelPuesto31);
        jPanelPuesto31.setLayout(jPanelPuesto31Layout);
        jPanelPuesto31Layout.setHorizontalGroup(
            jPanelPuesto31Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 14, Short.MAX_VALUE)
        );
        jPanelPuesto31Layout.setVerticalGroup(
            jPanelPuesto31Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 14, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 16;
        gridBagConstraints.gridy = 16;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel5.add(jPanelPuesto31, gridBagConstraints);

        jPanelPuesto27.setBackground(new java.awt.Color(0, 204, 51));
        jPanelPuesto27.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanelPuesto27.setMaximumSize(new java.awt.Dimension(20, 20));
        jPanelPuesto27.setMinimumSize(new java.awt.Dimension(20, 20));

        javax.swing.GroupLayout jPanelPuesto27Layout = new javax.swing.GroupLayout(jPanelPuesto27);
        jPanelPuesto27.setLayout(jPanelPuesto27Layout);
        jPanelPuesto27Layout.setHorizontalGroup(
            jPanelPuesto27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 14, Short.MAX_VALUE)
        );
        jPanelPuesto27Layout.setVerticalGroup(
            jPanelPuesto27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 14, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.insets = new java.awt.Insets(23, 0, 0, 0);
        jPanel5.add(jPanelPuesto27, gridBagConstraints);

        jPanelPuesto22.setBackground(new java.awt.Color(0, 204, 51));
        jPanelPuesto22.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanelPuesto22.setMaximumSize(new java.awt.Dimension(20, 20));
        jPanelPuesto22.setMinimumSize(new java.awt.Dimension(20, 20));

        javax.swing.GroupLayout jPanelPuesto22Layout = new javax.swing.GroupLayout(jPanelPuesto22);
        jPanelPuesto22.setLayout(jPanelPuesto22Layout);
        jPanelPuesto22Layout.setHorizontalGroup(
            jPanelPuesto22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 14, Short.MAX_VALUE)
        );
        jPanelPuesto22Layout.setVerticalGroup(
            jPanelPuesto22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 14, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 16;
        gridBagConstraints.gridy = 0;
        jPanel5.add(jPanelPuesto22, gridBagConstraints);

        jPanelPuesto28.setBackground(new java.awt.Color(0, 204, 51));
        jPanelPuesto28.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanelPuesto28.setMaximumSize(new java.awt.Dimension(20, 20));
        jPanelPuesto28.setMinimumSize(new java.awt.Dimension(20, 20));

        javax.swing.GroupLayout jPanelPuesto28Layout = new javax.swing.GroupLayout(jPanelPuesto28);
        jPanelPuesto28.setLayout(jPanelPuesto28Layout);
        jPanelPuesto28Layout.setHorizontalGroup(
            jPanelPuesto28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 14, Short.MAX_VALUE)
        );
        jPanelPuesto28Layout.setVerticalGroup(
            jPanelPuesto28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 14, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 16;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.insets = new java.awt.Insets(23, 0, 0, 0);
        jPanel5.add(jPanelPuesto28, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(104, 10, 0, 0);
        jPanel1.add(jPanel5, gridBagConstraints);

        jPanel11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel11.setMinimumSize(new java.awt.Dimension(100, 160));
        jPanel11.setPreferredSize(new java.awt.Dimension(100, 160));
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setText("Ingenierias");
        jPanel11.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 139, -1, -1));

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridheight = 9;
        gridBagConstraints.ipadx = 18;
        gridBagConstraints.ipady = 147;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel1.add(jPanel11, gridBagConstraints);

        jPanel28.setEnabled(false);
        jPanel28.setMinimumSize(new java.awt.Dimension(80, 132));
        jPanel28.setPreferredSize(new java.awt.Dimension(80, 132));
        java.awt.GridBagLayout jPanel28Layout = new java.awt.GridBagLayout();
        jPanel28Layout.columnWidths = new int[] {0, 8, 0, 8, 0, 8, 0, 8, 0, 8, 0};
        jPanel28Layout.rowHeights = new int[] {0, 4, 0, 4, 0, 4, 0, 4, 0, 4, 0, 4, 0, 4, 0, 4, 0};
        jPanel28.setLayout(jPanel28Layout);

        jPanelPuesto7.setBackground(new java.awt.Color(0, 204, 51));
        jPanelPuesto7.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanelPuesto7.setMaximumSize(new java.awt.Dimension(20, 20));
        jPanelPuesto7.setMinimumSize(new java.awt.Dimension(20, 20));

        javax.swing.GroupLayout jPanelPuesto7Layout = new javax.swing.GroupLayout(jPanelPuesto7);
        jPanelPuesto7.setLayout(jPanelPuesto7Layout);
        jPanelPuesto7Layout.setHorizontalGroup(
            jPanelPuesto7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 14, Short.MAX_VALUE)
        );
        jPanelPuesto7Layout.setVerticalGroup(
            jPanelPuesto7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 14, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        jPanel28.add(jPanelPuesto7, gridBagConstraints);

        jPanelPuesto10.setBackground(new java.awt.Color(0, 204, 51));
        jPanelPuesto10.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanelPuesto10.setMaximumSize(new java.awt.Dimension(20, 20));
        jPanelPuesto10.setMinimumSize(new java.awt.Dimension(20, 20));

        javax.swing.GroupLayout jPanelPuesto10Layout = new javax.swing.GroupLayout(jPanelPuesto10);
        jPanelPuesto10.setLayout(jPanelPuesto10Layout);
        jPanelPuesto10Layout.setHorizontalGroup(
            jPanelPuesto10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 14, Short.MAX_VALUE)
        );
        jPanelPuesto10Layout.setVerticalGroup(
            jPanelPuesto10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 14, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 10;
        gridBagConstraints.gridy = 0;
        jPanel28.add(jPanelPuesto10, gridBagConstraints);

        jPanelPuesto5.setBackground(new java.awt.Color(0, 204, 51));
        jPanelPuesto5.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanelPuesto5.setMaximumSize(new java.awt.Dimension(20, 20));
        jPanelPuesto5.setMinimumSize(new java.awt.Dimension(20, 20));

        javax.swing.GroupLayout jPanelPuesto5Layout = new javax.swing.GroupLayout(jPanelPuesto5);
        jPanelPuesto5.setLayout(jPanelPuesto5Layout);
        jPanelPuesto5Layout.setHorizontalGroup(
            jPanelPuesto5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 14, Short.MAX_VALUE)
        );
        jPanelPuesto5Layout.setVerticalGroup(
            jPanelPuesto5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 14, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel28.add(jPanelPuesto5, gridBagConstraints);

        jPanel32.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel32.setMaximumSize(new java.awt.Dimension(10, 10));
        jPanel32.setMinimumSize(new java.awt.Dimension(10, 10));
        jPanel32.setPreferredSize(new java.awt.Dimension(20, 20));

        javax.swing.GroupLayout jPanel32Layout = new javax.swing.GroupLayout(jPanel32);
        jPanel32.setLayout(jPanel32Layout);
        jPanel32Layout.setHorizontalGroup(
            jPanel32Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 14, Short.MAX_VALUE)
        );
        jPanel32Layout.setVerticalGroup(
            jPanel32Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 14, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        jPanel28.add(jPanel32, gridBagConstraints);

        jPanelPuesto3.setBackground(new java.awt.Color(0, 204, 51));
        jPanelPuesto3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanelPuesto3.setMaximumSize(new java.awt.Dimension(20, 20));
        jPanelPuesto3.setMinimumSize(new java.awt.Dimension(20, 20));

        javax.swing.GroupLayout jPanelPuesto3Layout = new javax.swing.GroupLayout(jPanelPuesto3);
        jPanelPuesto3.setLayout(jPanelPuesto3Layout);
        jPanelPuesto3Layout.setHorizontalGroup(
            jPanelPuesto3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 14, Short.MAX_VALUE)
        );
        jPanelPuesto3Layout.setVerticalGroup(
            jPanelPuesto3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 14, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel28.add(jPanelPuesto3, gridBagConstraints);

        jPanelPuesto1.setBackground(new java.awt.Color(0, 204, 51));
        jPanelPuesto1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanelPuesto1.setMaximumSize(new java.awt.Dimension(20, 20));
        jPanelPuesto1.setMinimumSize(new java.awt.Dimension(20, 20));
        jPanelPuesto1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelPuesto1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanelPuesto1Layout = new javax.swing.GroupLayout(jPanelPuesto1);
        jPanelPuesto1.setLayout(jPanelPuesto1Layout);
        jPanelPuesto1Layout.setHorizontalGroup(
            jPanelPuesto1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 16, Short.MAX_VALUE)
        );
        jPanelPuesto1Layout.setVerticalGroup(
            jPanelPuesto1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 16, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 16;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel28.add(jPanelPuesto1, gridBagConstraints);

        jPanelPuesto8.setBackground(new java.awt.Color(0, 204, 51));
        jPanelPuesto8.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanelPuesto8.setMaximumSize(new java.awt.Dimension(20, 20));
        jPanelPuesto8.setMinimumSize(new java.awt.Dimension(20, 20));

        javax.swing.GroupLayout jPanelPuesto8Layout = new javax.swing.GroupLayout(jPanelPuesto8);
        jPanelPuesto8.setLayout(jPanelPuesto8Layout);
        jPanelPuesto8Layout.setHorizontalGroup(
            jPanelPuesto8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 14, Short.MAX_VALUE)
        );
        jPanelPuesto8Layout.setVerticalGroup(
            jPanelPuesto8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 14, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 10;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel28.add(jPanelPuesto8, gridBagConstraints);

        jPanelPuesto2.setBackground(new java.awt.Color(0, 204, 51));
        jPanelPuesto2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanelPuesto2.setMaximumSize(new java.awt.Dimension(20, 20));
        jPanelPuesto2.setMinimumSize(new java.awt.Dimension(20, 20));

        javax.swing.GroupLayout jPanelPuesto2Layout = new javax.swing.GroupLayout(jPanelPuesto2);
        jPanelPuesto2.setLayout(jPanelPuesto2Layout);
        jPanelPuesto2Layout.setHorizontalGroup(
            jPanelPuesto2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 14, Short.MAX_VALUE)
        );
        jPanelPuesto2Layout.setVerticalGroup(
            jPanelPuesto2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 14, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 10;
        gridBagConstraints.gridy = 16;
        jPanel28.add(jPanelPuesto2, gridBagConstraints);

        jPanelPuesto9.setBackground(new java.awt.Color(0, 204, 51));
        jPanelPuesto9.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanelPuesto9.setMaximumSize(new java.awt.Dimension(20, 20));
        jPanelPuesto9.setMinimumSize(new java.awt.Dimension(20, 20));

        javax.swing.GroupLayout jPanelPuesto9Layout = new javax.swing.GroupLayout(jPanelPuesto9);
        jPanelPuesto9.setLayout(jPanelPuesto9Layout);
        jPanelPuesto9Layout.setHorizontalGroup(
            jPanelPuesto9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 14, Short.MAX_VALUE)
        );
        jPanelPuesto9Layout.setVerticalGroup(
            jPanelPuesto9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 14, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel28.add(jPanelPuesto9, gridBagConstraints);

        jPanelPuesto6.setBackground(new java.awt.Color(0, 204, 51));
        jPanelPuesto6.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanelPuesto6.setMaximumSize(new java.awt.Dimension(20, 20));
        jPanelPuesto6.setMinimumSize(new java.awt.Dimension(20, 20));

        javax.swing.GroupLayout jPanelPuesto6Layout = new javax.swing.GroupLayout(jPanelPuesto6);
        jPanelPuesto6.setLayout(jPanelPuesto6Layout);
        jPanelPuesto6Layout.setHorizontalGroup(
            jPanelPuesto6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 14, Short.MAX_VALUE)
        );
        jPanelPuesto6Layout.setVerticalGroup(
            jPanelPuesto6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 14, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 10;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel28.add(jPanelPuesto6, gridBagConstraints);

        jPanelPuesto4.setBackground(new java.awt.Color(0, 204, 51));
        jPanelPuesto4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanelPuesto4.setMaximumSize(new java.awt.Dimension(20, 20));
        jPanelPuesto4.setMinimumSize(new java.awt.Dimension(20, 20));

        javax.swing.GroupLayout jPanelPuesto4Layout = new javax.swing.GroupLayout(jPanelPuesto4);
        jPanelPuesto4.setLayout(jPanelPuesto4Layout);
        jPanelPuesto4Layout.setHorizontalGroup(
            jPanelPuesto4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 14, Short.MAX_VALUE)
        );
        jPanelPuesto4Layout.setVerticalGroup(
            jPanelPuesto4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 14, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 10;
        gridBagConstraints.gridy = 12;
        jPanel28.add(jPanelPuesto4, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 10;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridheight = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(9, 66, 0, 0);
        jPanel1.add(jPanel28, gridBagConstraints);

        jPanel13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel13.setMinimumSize(new java.awt.Dimension(100, 100));
        jPanel13.setPreferredSize(new java.awt.Dimension(100, 100));
        java.awt.GridBagLayout jPanel13Layout = new java.awt.GridBagLayout();
        jPanel13Layout.columnWidths = new int[] {0, 11, 0, 11, 0, 11, 0};
        jPanel13Layout.rowHeights = new int[] {0, 5, 0, 5, 0};
        jPanel13.setLayout(jPanel13Layout);

        jPanel52.setBackground(new java.awt.Color(51, 204, 0));
        jPanel52.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel52.setMaximumSize(new java.awt.Dimension(20, 20));
        jPanel52.setMinimumSize(new java.awt.Dimension(20, 20));

        javax.swing.GroupLayout jPanel52Layout = new javax.swing.GroupLayout(jPanel52);
        jPanel52.setLayout(jPanel52Layout);
        jPanel52Layout.setHorizontalGroup(
            jPanel52Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 14, Short.MAX_VALUE)
        );
        jPanel52Layout.setVerticalGroup(
            jPanel52Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 14, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel13.add(jPanel52, gridBagConstraints);

        jPanel53.setBackground(new java.awt.Color(255, 0, 0));
        jPanel53.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel53.setMaximumSize(new java.awt.Dimension(20, 20));
        jPanel53.setMinimumSize(new java.awt.Dimension(20, 20));

        javax.swing.GroupLayout jPanel53Layout = new javax.swing.GroupLayout(jPanel53);
        jPanel53.setLayout(jPanel53Layout);
        jPanel53Layout.setHorizontalGroup(
            jPanel53Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 14, Short.MAX_VALUE)
        );
        jPanel53Layout.setVerticalGroup(
            jPanel53Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 14, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel13.add(jPanel53, gridBagConstraints);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Libre");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        jPanel13.add(jLabel1, gridBagConstraints);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("ocupado");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        jPanel13.add(jLabel2, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 10;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        jPanel1.add(jPanel13, gridBagConstraints);

        jPanel4.setEnabled(false);
        jPanel4.setMinimumSize(new java.awt.Dimension(150, 150));
        jPanel4.setPreferredSize(new java.awt.Dimension(150, 150));
        java.awt.GridBagLayout jPanel4Layout = new java.awt.GridBagLayout();
        jPanel4Layout.columnWidths = new int[] {0, 11, 0, 11, 0, 11, 0, 11, 0};
        jPanel4Layout.rowHeights = new int[] {0, 5, 0, 5, 0, 5, 0, 5, 0};
        jPanel4.setLayout(jPanel4Layout);

        jPanelPuesto17.setBackground(new java.awt.Color(0, 204, 51));
        jPanelPuesto17.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanelPuesto17.setMaximumSize(new java.awt.Dimension(20, 20));
        jPanelPuesto17.setMinimumSize(new java.awt.Dimension(20, 20));

        javax.swing.GroupLayout jPanelPuesto17Layout = new javax.swing.GroupLayout(jPanelPuesto17);
        jPanelPuesto17.setLayout(jPanelPuesto17Layout);
        jPanelPuesto17Layout.setHorizontalGroup(
            jPanelPuesto17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 14, Short.MAX_VALUE)
        );
        jPanelPuesto17Layout.setVerticalGroup(
            jPanelPuesto17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 14, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel4.add(jPanelPuesto17, gridBagConstraints);

        jPanelPuesto18.setBackground(new java.awt.Color(0, 204, 51));
        jPanelPuesto18.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanelPuesto18.setMaximumSize(new java.awt.Dimension(20, 20));
        jPanelPuesto18.setMinimumSize(new java.awt.Dimension(20, 20));

        javax.swing.GroupLayout jPanelPuesto18Layout = new javax.swing.GroupLayout(jPanelPuesto18);
        jPanelPuesto18.setLayout(jPanelPuesto18Layout);
        jPanelPuesto18Layout.setHorizontalGroup(
            jPanelPuesto18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 14, Short.MAX_VALUE)
        );
        jPanelPuesto18Layout.setVerticalGroup(
            jPanelPuesto18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 14, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        jPanel4.add(jPanelPuesto18, gridBagConstraints);

        jPanelPuesto14.setBackground(new java.awt.Color(0, 204, 51));
        jPanelPuesto14.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanelPuesto14.setMaximumSize(new java.awt.Dimension(20, 20));
        jPanelPuesto14.setMinimumSize(new java.awt.Dimension(20, 20));

        javax.swing.GroupLayout jPanelPuesto14Layout = new javax.swing.GroupLayout(jPanelPuesto14);
        jPanelPuesto14.setLayout(jPanelPuesto14Layout);
        jPanelPuesto14Layout.setHorizontalGroup(
            jPanelPuesto14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 14, Short.MAX_VALUE)
        );
        jPanelPuesto14Layout.setVerticalGroup(
            jPanelPuesto14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 14, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        jPanel4.add(jPanelPuesto14, gridBagConstraints);

        jPanelPuesto15.setBackground(new java.awt.Color(0, 204, 51));
        jPanelPuesto15.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanelPuesto15.setMaximumSize(new java.awt.Dimension(20, 20));
        jPanelPuesto15.setMinimumSize(new java.awt.Dimension(20, 20));

        javax.swing.GroupLayout jPanelPuesto15Layout = new javax.swing.GroupLayout(jPanelPuesto15);
        jPanelPuesto15.setLayout(jPanelPuesto15Layout);
        jPanelPuesto15Layout.setHorizontalGroup(
            jPanelPuesto15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 14, Short.MAX_VALUE)
        );
        jPanelPuesto15Layout.setVerticalGroup(
            jPanelPuesto15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 14, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel4.add(jPanelPuesto15, gridBagConstraints);

        jPanelPuesto16.setBackground(new java.awt.Color(0, 204, 51));
        jPanelPuesto16.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanelPuesto16.setMaximumSize(new java.awt.Dimension(20, 20));
        jPanelPuesto16.setMinimumSize(new java.awt.Dimension(20, 20));

        javax.swing.GroupLayout jPanelPuesto16Layout = new javax.swing.GroupLayout(jPanelPuesto16);
        jPanelPuesto16.setLayout(jPanelPuesto16Layout);
        jPanelPuesto16Layout.setHorizontalGroup(
            jPanelPuesto16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 14, Short.MAX_VALUE)
        );
        jPanelPuesto16Layout.setVerticalGroup(
            jPanelPuesto16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 14, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel4.add(jPanelPuesto16, gridBagConstraints);

        jPanelPuesto11.setBackground(new java.awt.Color(0, 204, 51));
        jPanelPuesto11.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanelPuesto11.setMaximumSize(new java.awt.Dimension(20, 20));
        jPanelPuesto11.setMinimumSize(new java.awt.Dimension(20, 20));

        javax.swing.GroupLayout jPanelPuesto11Layout = new javax.swing.GroupLayout(jPanelPuesto11);
        jPanelPuesto11.setLayout(jPanelPuesto11Layout);
        jPanelPuesto11Layout.setHorizontalGroup(
            jPanelPuesto11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 14, Short.MAX_VALUE)
        );
        jPanelPuesto11Layout.setVerticalGroup(
            jPanelPuesto11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 14, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        jPanel4.add(jPanelPuesto11, gridBagConstraints);

        jPanelPuesto12.setBackground(new java.awt.Color(0, 204, 51));
        jPanelPuesto12.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanelPuesto12.setMaximumSize(new java.awt.Dimension(20, 20));
        jPanelPuesto12.setMinimumSize(new java.awt.Dimension(20, 20));

        javax.swing.GroupLayout jPanelPuesto12Layout = new javax.swing.GroupLayout(jPanelPuesto12);
        jPanelPuesto12.setLayout(jPanelPuesto12Layout);
        jPanelPuesto12Layout.setHorizontalGroup(
            jPanelPuesto12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 14, Short.MAX_VALUE)
        );
        jPanelPuesto12Layout.setVerticalGroup(
            jPanelPuesto12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 14, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 4;
        jPanel4.add(jPanelPuesto12, gridBagConstraints);

        jPanelPuesto19.setBackground(new java.awt.Color(0, 204, 51));
        jPanelPuesto19.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanelPuesto19.setMaximumSize(new java.awt.Dimension(20, 20));
        jPanelPuesto19.setMinimumSize(new java.awt.Dimension(20, 20));

        javax.swing.GroupLayout jPanelPuesto19Layout = new javax.swing.GroupLayout(jPanelPuesto19);
        jPanelPuesto19.setLayout(jPanelPuesto19Layout);
        jPanelPuesto19Layout.setHorizontalGroup(
            jPanelPuesto19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 14, Short.MAX_VALUE)
        );
        jPanelPuesto19Layout.setVerticalGroup(
            jPanelPuesto19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 14, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 0;
        jPanel4.add(jPanelPuesto19, gridBagConstraints);

        jPanelPuesto13.setBackground(new java.awt.Color(0, 204, 51));
        jPanelPuesto13.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanelPuesto13.setMaximumSize(new java.awt.Dimension(20, 20));
        jPanelPuesto13.setMinimumSize(new java.awt.Dimension(20, 20));

        javax.swing.GroupLayout jPanelPuesto13Layout = new javax.swing.GroupLayout(jPanelPuesto13);
        jPanelPuesto13.setLayout(jPanelPuesto13Layout);
        jPanelPuesto13Layout.setHorizontalGroup(
            jPanelPuesto13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 14, Short.MAX_VALUE)
        );
        jPanelPuesto13Layout.setVerticalGroup(
            jPanelPuesto13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 14, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 4;
        jPanel4.add(jPanelPuesto13, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(4, 9, 0, 0);
        jPanel1.add(jPanel4, gridBagConstraints);

        jPanel3.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel3.setName(""); // NOI18N
        jPanel3.setLayout(new java.awt.GridBagLayout());

        jLabel5.setText("porteria sur (control entrada)");
        jLabel5.setToolTipText("");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(26, 21, 27, 21);
        jPanel3.add(jLabel5, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 10;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 25, 0);
        jPanel1.add(jPanel3, gridBagConstraints);

        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel6.setMinimumSize(new java.awt.Dimension(60, 60));
        jPanel6.setPreferredSize(new java.awt.Dimension(60, 60));
        jPanel6.setLayout(new java.awt.GridBagLayout());

        jLabel6.setText("IPET");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(24, 19, 22, 19);
        jPanel6.add(jLabel6, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 100, 0);
        jPanel1.add(jPanel6, gridBagConstraints);

        jPanel7.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel7.setMinimumSize(new java.awt.Dimension(185, 69));
        jPanel7.setPreferredSize(new java.awt.Dimension(183, 67));
        jPanel7.setLayout(new java.awt.GridBagLayout());

        jLabel7.setText("Porteria norte (control salida)");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(24, 19, 29, 23);
        jPanel7.add(jLabel7, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 25, 21);
        jPanel1.add(jPanel7, gridBagConstraints);

        jPanel8.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 102, 0)));
        jPanel8.setMinimumSize(new java.awt.Dimension(70, 150));
        jPanel8.setPreferredSize(new java.awt.Dimension(70, 150));
        jPanel8.setLayout(new java.awt.GridBagLayout());

        jLabel8.setText("Parque");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(65, 19, 71, 17);
        jPanel8.add(jLabel8, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.insets = new java.awt.Insets(45, 0, 0, 0);
        jPanel1.add(jPanel8, gridBagConstraints);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("MAPA PARQUEADERO");
        getContentPane().add(jLabel4, java.awt.BorderLayout.PAGE_START);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Acciones"));
        java.awt.GridBagLayout jPanel2Layout1 = new java.awt.GridBagLayout();
        jPanel2Layout1.columnWidths = new int[] {0, 9, 0, 9, 0};
        jPanel2Layout1.rowHeights = new int[] {0, 4, 0, 4, 0, 4, 0, 4, 0, 4, 0, 4, 0};
        jPanel2.setLayout(jPanel2Layout1);

        jButtonCerrar.setText("cerrar");
        jButtonCerrar.setMaximumSize(new java.awt.Dimension(95, 23));
        jButtonCerrar.setMinimumSize(new java.awt.Dimension(95, 23));
        jButtonCerrar.setPreferredSize(new java.awt.Dimension(95, 23));
        jButtonCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCerrarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(18, 14, 2, 0);
        jPanel2.add(jButtonCerrar, gridBagConstraints);

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPanelPuesto1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelPuesto1MouseClicked
        if(!jPanelPuesto1.getBackground().equals(Color.red)){
            
            //con.setId(principal.);
            LugarMapa lugar = new LugarMapa();
            lugar.setObjCon(objCon);
            lugar.setObjVeh(objVeh);
            lugar.setLugar(jPanelPuesto1);
            boolean bandera = gMapa.asginarLugar(lugar,objVeh.getPlaca());
            if (bandera){
                jPanelPuesto1.setBackground(Color.red);
                JOptionPane.showMessageDialog(null, "lugar asignado\nDatos del conductor: \nID: "
                + " "+ objCon.getId()+"\nNombre: "+objCon.getNombres()+" "+objCon.getApellidos()+
                "\nPlaca vehiculo: "+objVeh.getPlaca());
            }
        }
    }//GEN-LAST:event_jPanelPuesto1MouseClicked

    private void jButtonCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCerrarActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_jButtonCerrarActionPerformed

   

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCerrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel28;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel32;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel52;
    private javax.swing.JPanel jPanel53;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanelPuesto1;
    private javax.swing.JPanel jPanelPuesto10;
    private javax.swing.JPanel jPanelPuesto11;
    private javax.swing.JPanel jPanelPuesto12;
    private javax.swing.JPanel jPanelPuesto13;
    private javax.swing.JPanel jPanelPuesto14;
    private javax.swing.JPanel jPanelPuesto15;
    private javax.swing.JPanel jPanelPuesto16;
    private javax.swing.JPanel jPanelPuesto17;
    private javax.swing.JPanel jPanelPuesto18;
    private javax.swing.JPanel jPanelPuesto19;
    private javax.swing.JPanel jPanelPuesto2;
    private javax.swing.JPanel jPanelPuesto20;
    private javax.swing.JPanel jPanelPuesto21;
    private javax.swing.JPanel jPanelPuesto22;
    private javax.swing.JPanel jPanelPuesto23;
    private javax.swing.JPanel jPanelPuesto24;
    private javax.swing.JPanel jPanelPuesto25;
    private javax.swing.JPanel jPanelPuesto26;
    private javax.swing.JPanel jPanelPuesto27;
    private javax.swing.JPanel jPanelPuesto28;
    private javax.swing.JPanel jPanelPuesto29;
    private javax.swing.JPanel jPanelPuesto3;
    private javax.swing.JPanel jPanelPuesto30;
    private javax.swing.JPanel jPanelPuesto31;
    private javax.swing.JPanel jPanelPuesto4;
    private javax.swing.JPanel jPanelPuesto5;
    private javax.swing.JPanel jPanelPuesto6;
    private javax.swing.JPanel jPanelPuesto7;
    private javax.swing.JPanel jPanelPuesto8;
    private javax.swing.JPanel jPanelPuesto9;
    // End of variables declaration//GEN-END:variables
}



